version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ~/jsf-webapp:/app
    depends_on:
      - database
    environment:
      MYSQL_DATABASE: jdbc:mysql://database:3306/javawebtutor
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    command: >
      sh -c "/bin/sh run_server.sh SampleWebApp; \
          tail -f /dev/null;"

    links:
      - database:database
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3307:3306"