INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (1, 'food', 'lemon grass', 25, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (2, 'food', 'squash', 40, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (3, 'food', 'lettuce', 36, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (4, 'food', 'sauerkraut', 40, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (5, 'food', 'spinach', 21, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (6, 'food', 'cream cheese', 10, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (7, 'food', 'garlic', 48, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (8, 'food', 'chile peppers', 31, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (9, 'food', 'vanilla bean', 29, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (10, 'food', 'pumpkins', 9, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (11, 'food', 'green onions', 38, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (12, 'food', 'black olives', 12, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (13, 'food', 'unsweetened chocolate', 44, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (14, 'food', 'beans', 39, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (15, 'food', 'anchovy paste', 25, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (16, 'food', 'Romano cheese', 16, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (17, 'food', 'apricots', 15, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (18, 'food', 'walnuts', 18, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (19, 'food', 'cactus', 31, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (20, 'food', 'carrots', 39, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (21, 'drink', 'avocado', 17, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (22, 'drink', 'pomegranate', 6, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (23, 'drink', 'lemon', 29, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (24, 'drink', 'orange', 10, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (25, 'drink', 'peach', 17, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (26, 'drink', 'raspberry', 22, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (27, 'drink', 'Sidecar', 8, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (28, 'drink', 'Whiskey Sour', 9, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (29, 'drink', 'Gin Gimlet', 9, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (30, 'drink', 'El Presidente', 24, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (31, 'drink', 'Electric Lemonade', 29, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (32, 'drink', 'Mai Tai', 10, 1);
INSERT INTO javawebtutor.Menu (id, kind, name, price, status) VALUES (33, 'drink', 'Hurricane', 6, 1);